### ISSUE TITLE
import name error

### ISSUE THREAD

**Issue by SolarWindRider** [Lichang-Chen/InstructZero#5]
Traceback (most recent call last):
  File "/content/InstructZero/InstructZero/experiments/run_instructzero.py", line 5, in <module>
    from automatic_prompt_engineer import ape, data
  File "/usr/local/lib/python3.10/dist-packages/automatic_prompt_engineer-0.1-py3.10.egg/automatic_prompt_engineer/ape.py", line 2, in <module>
    from automatic_prompt_engineering import generate, evaluate, config, template, data, llm
ModuleNotFoundError: **No module named 'automatic_prompt_engineering**'

**automatic_prompt_engineering should rename as automatic_prompt_engineering**

**Comment by Lichang-Chen** [comment]
Thanks for your question. Please refer to out lastest version!
